Category.create(name: "内科")
Category.create(name: "外科")
Category.create(name: "整形外科")
Category.create(name: "皮膚科")
Category.create(name: "眼科")
Category.create(name: "耳鼻科")
Category.create(name: "歯科")
Category.create(name: "その他")